//----------------------
// <auto-generated>
//     GENERATED BY ZEBBLE
// </auto-generated>
#pragma warning disable  IDE0017, CS0108, CS0436
//----------------------

#region UI.Templates.Blank
namespace UI.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Templates\Blank.zbl")]
    partial class Blank : Page
    {
        public ScrollView Body = new ScrollView();
        public Stack Wrapper = new Stack();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Body.Id = "Body";
            Body.CssClass = "Body";

            Wrapper.Id = "Wrapper";
            Wrapper.CssClass = "Wrapper";

            await Body.Add(Wrapper);
            await Add(Body);
        }
    }
}
#endregion

#region UI.Pages.Page1
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Page1.zbl")]
    partial class Page1 : Templates.Empty
    {
        public ScrollView Scroller = new ScrollView();
        public ListView<Domain.Category, CategoryRow> CategoriesList = new ListView<Domain.Category, CategoryRow>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Scroller.Id = "Scroller";
            Scroller.CssClass = "Scroller";

            CategoriesList.Id = "CategoriesList";

            var __center1 = new Center();

            var __primaryButton1 = new PrimaryButton() { CssClass = "SecondaryButton", Text = "Change Theme" }.On(x => x.Tapped, OnDarkTapped);

            await __center1.Add(__primaryButton1);
            await Scroller.AddRange(new View[] { CategoriesList, __center1 });
            await Body.Add(Scroller);
        }

        [EscapeGCop("Auto-generated")]
        [SourceCode(@"Views\Pages\Page1.zbl")]
        public partial class CategoryRow : ListViewItem<Domain.Category>
        {
            public UI.Modules.SubjectsPreview LikedSubjects = new UI.Modules.SubjectsPreview();
            protected override async Task InitializeFromMarkup()
            {
                await base.InitializeFromMarkup();

                LikedSubjects.Id = "LikedSubjects";
                LikedSubjects.CssClass = "Recycler";
                LikedSubjects.Bind("Category", () => Category, x=>x).Bind("HeaderText", () => Category, x=>x.Name);

                await Add(LikedSubjects);
            }
            }}
        }
        #endregion

#region UI.Pages.Page2
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Page2.zbl")]
    partial class Page2 : Templates.Empty
    {
        public ScrollView Scroller = new ScrollView();
        public ListView<Domain.WordInfo,DetailRow> DetailsList = new ListView<Domain.WordInfo,DetailRow>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Scroller.Id = "Scroller";
            Scroller.CssClass = "Scroller";

            var __center1 = new Center();

            var __primaryButton1 = new PrimaryButton() { CssClass = "SecondaryButton", Text = "Back" }.On(x => x.Tapped, BackTapped);

            DetailsList.Id = "DetailsList";

            await __center1.Add(__primaryButton1);
            await Scroller.AddRange(new View[] { __center1, DetailsList });
            await Body.Add(Scroller);
        }

        [EscapeGCop("Auto-generated")]
        [SourceCode(@"Views\Pages\Page2.zbl")]
        public partial class DetailRow : ListViewItem<Domain.WordInfo>
        {
            public TextView Text1 = new TextView();
            public TextView Text2 = new TextView();
            public TextView Text3 = new TextView();
            protected override async Task InitializeFromMarkup()
            {
                await base.InitializeFromMarkup();

                var __center1 = new Center();

                var __stack1 = new Stack() { CssClass = "DetailStack" };

                Text1.Id = "Text1";

                Text2.Id = "Text2";

                Text3.Id = "Text3";

                await __stack1.AddRange(new View[] { Text1, Text2, Text3 });
                await __center1.Add(__stack1);
                await Add(__center1);
            }
            }}
        }
        #endregion

#region UI.Modules.SubjectsPreview
namespace UI.Modules
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Components\SubjectsPreview.zbl")]
    partial class SubjectsPreview : Stack
    {
        public TextView RowHeader = new TextView();
        public RecyclerCarousel<Subject, SlideTemplate> Carousel = new RecyclerCarousel<Subject, SlideTemplate>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            this.ClipChildren = false;

            var __row1 = new Row();

            RowHeader.Id = "RowHeader";
            RowHeader.CssClass = "HeaderText";
            RowHeader.Wrap = false;

            var __row2 = new Row();

            Carousel.Id = "Carousel";
            Carousel.ShowBullets = false;
            Carousel.CenterAligned = false;
            Carousel.ClipChildren = true;

            await __row1.Add(RowHeader);
            await __row2.Add(Carousel);
            await AddRange(new View[] { __row1, __row2 });
        }

        [EscapeGCop("Auto-generated")]
        [SourceCode(@"Views\Pages\Components\SubjectsPreview.zbl")]
        public partial class SlideTemplate : RecyclerCarouselSlide<Subject>
        {
            public WordListCard WordListCard = new WordListCard();
            protected override async Task InitializeFromMarkup()
            {
                await base.InitializeFromMarkup();

                this.ClipChildren = false;

                WordListCard.Id = "WordListCard";

                await Add(WordListCard);
            }
            }}
        }
        #endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "QgOc1JkFgLLH21blkf7xuvmUIRM";
    }
}
